// 🧘 LINIȘTE ȘI ECHILIBRU - 600 AFIRMAȚII
// Inspirat de Neville Goddard, Joe Dispenza, Louise Hay, Abraham Hicks

export const calm_600 = {
  // 🌅 DIMINEAȚA - 100 afirmații (pace și deschidere)
  morning: [
    // Neville Goddard - Imaginația și starea de liniște
    "Sunt deja în starea de liniște perfectă.",
    "Imaginația mea creează realitatea păcii.",
    "Sunt în starea deja fiind calm și echilibrat.",
    "Realitatea mea reflectă liniștea din imaginația mea.",
    "Sunt deja în starea de pace completă.",
    "Imaginația mea este cheia liniștii mele.",
    "Sunt în starea deja fiind în armonie.",
    "Realitatea păcii se manifestă prin imaginația mea.",
    "Sunt deja în starea de echilibru perfect.",
    "Imaginația mea creează liniștea în realitate.",
    
    // Joe Dispenza - Neuroplasticitate și liniște
    "Îmi reprogramez creierul pentru liniște perfectă.",
    "Noua mea identitate este cea a unei persoane calme.",
    "Îmi schimb starea interioară pentru pace.",
    "Creierul meu se reconectează pentru liniște.",
    "Sunt în procesul de a deveni o persoană calmă.",
    "Îmi creez o nouă identitate de pace.",
    "Starea mea interioară atrage liniștea.",
    "Îmi reprogramez gândurile pentru echilibru.",
    "Sunt în transformare către pace completă.",
    "Noua mea identitate reflectă liniștea perfectă.",
    
    // Louise Hay - Iubirea de sine și acceptarea păcii
    "Îmi iubesc și accept liniștea în toate formele.",
    "Merit toate formele de pace și echilibru.",
    "Sunt demn de liniște și armonie.",
    "Îmi permit să fiu calm și echilibrat.",
    "Sunt în pace cu liniștea și echilibrul meu.",
    "Îmi iubesc și accept toate aspectele păcii.",
    "Sunt demn de toate formele de liniște.",
    "Îmi accept pacea cu dragoste.",
    "Sunt în armonie cu toate formele de liniște.",
    "Îmi iubesc și accept toate aspectele echilibrului.",
    
    // Abraham Hicks - Vibrația și atracția păcii
    "Vibrația mea atrage liniștea natural.",
    "Sunt în aliniere cu pacea Universului.",
    "Energia mea curge către echilibru.",
    "Sunt un magnet pentru liniște și pace.",
    "Vibrația păcii curge prin mine.",
    "Sunt în rezonanță cu armonia.",
    "Energia mea atrage liniște cu ușurință.",
    "Sunt în aliniere cu pacea infinită.",
    "Vibrația mea creează echilibru.",
    "Sunt un canal pentru liniștea Universului.",
    
    // Afirmații combinate - dimineața
    "Sunt deja calm și liniștea curge prin mine.",
    "Imaginația mea creează realitatea păcii perfecte.",
    "Îmi reprogramez creierul pentru liniște în fiecare dimineață.",
    "Îmi iubesc și accept toate formele de pace.",
    "Vibrația mea atrage liniște și echilibru natural.",
    "Sunt în starea deja fiind în pace perfectă.",
    "Noua mea identitate reflectă liniștea infinită.",
    "Îmi permit să fiu calm și echilibrat în toate aspectele.",
    "Energia păcii curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru liniște și armonie.",
    
    // Liniște specifică - dimineața
    "Liniștea vine către mine din toate direcțiile.",
    "Sunt deschis la toate oportunitățile de pace.",
    "Liniștea este starea mea naturală.",
    "Sunt un magnet pentru momente de calm.",
    "Echilibrul mă găsește ușor.",
    "Sunt recunoscător pentru toate formele de liniște.",
    "Pacea circulă liber în viața mea.",
    "Sunt deschis la toate formele de echilibru.",
    "Armonia vine către mine natural.",
    "Sunt un magnet pentru liniște reciprocă.",
    
    // Pace și echilibru - dimineața
    "Echilibrul vine către mine natural și ușor.",
    "Sunt demn de toate formele de liniște.",
    "Echilibrul este parte din identitatea mea.",
    "Sunt un magnet pentru momente de pace.",
    "Echilibrul curge prin toate aspectele vieții mele.",
    "Sunt recunoscător pentru toate momentele de liniște.",
    "Echilibrul este starea mea naturală.",
    "Sunt deschis la toate formele de pace.",
    "Armonia vine către mine cu ușurință.",
    "Sunt un canal pentru liniștea infinită.",
    
    // Energie și deschidere - dimineața
    "Energia păcii curge prin mine în fiecare dimineață.",
    "Sunt deschis la toate oportunitățile de liniște de azi.",
    "Energia echilibrului vine către mine din toate direcțiile.",
    "Sunt pregătit să primesc toate binecuvântările de pace.",
    "Energia liniștii vibrează în fiecare celulă a corpului meu.",
    "Sunt deschis la toate formele de echilibru.",
    "Energia păcii curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru oportunități de liniște.",
    "Energia mea atrage pace și echilibru.",
    "Sunt deschis la toate sursele de liniște infinită.",
    
    // Gratitudine și recunoaștere - dimineața
    "Sunt recunoscător pentru toate momentele de liniște din viața mea.",
    "Mulțumesc pentru toate sursele de pace.",
    "Sunt recunoscător pentru liniștea care curge prin mine.",
    "Mulțumesc pentru toate aspectele echilibrului din viața mea.",
    "Sunt recunoscător pentru pacea din viața mea.",
    "Mulțumesc pentru toate formele de liniște.",
    "Sunt recunoscător pentru toate momentele de calm.",
    "Mulțumesc pentru liniștea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de pace.",
    "Mulțumesc pentru liniștea care curge prin mine.",
    
    // Manifestare și creare - dimineața
    "Creez liniște perfectă prin gândurile mele pozitive.",
    "Manifest pace în toate aspectele vieții mele.",
    "Creez echilibru prin intenția mea clară.",
    "Manifest liniște prin credința mea în pace.",
    "Creez armonie prin acțiunile mele calme.",
    "Manifest pace prin gratitudinea mea pentru liniște.",
    "Creez echilibru prin vibrația mea pozitivă.",
    "Manifest liniște prin perseverența mea în pace.",
    "Creez armonie prin deschiderea mea la liniște.",
    "Manifest pace prin iubirea mea pentru viață.",
    
    // Identitate și valoare - dimineața
    "Sunt o persoană calmă și echilibrată.",
    "Identitatea mea reflectă liniștea și pacea.",
    "Sunt demn de toate formele de liniște.",
    "Valoarea mea atrage pace natural.",
    "Sunt o persoană de liniște în toate aspectele.",
    "Identitatea mea vibrează cu echilibrul.",
    "Sunt demn de toate oportunitățile de pace.",
    "Valoarea mea se reflectă în liniștea din viața mea.",
    "Sunt o persoană care creează echilibru.",
    "Identitatea mea este cea a unei persoane calme.",
    
    // Acțiune și implementare - dimineața
    "Acționez cu înțelepciune pentru liniște.",
    "Implementez strategii de pace.",
    "Acționez cu curaj pentru echilibru.",
    "Implementez planuri de liniște.",
    "Acționez cu determinare pentru pace.",
    "Implementez strategii de echilibru.",
    "Acționez cu înțelepciune pentru armonie.",
    "Implementez planuri de pace.",
    "Acționez cu curaj pentru liniște.",
    "Implementez strategii de echilibru durabil."
  ],
  
  // ☀️ DUPĂ-AMIAZA - 100 afirmații (recunoaștere și dezvoltare)
  afternoon: [
    // Neville Goddard - Persistența în starea de liniște
    "Persist în starea de liniște perfectă.",
    "Mă mențin în starea deja fiind calm.",
    "Persist în imaginația păcii.",
    "Mă mențin în starea de echilibru complet.",
    "Persist în starea deja fiind în pace.",
    "Mă mențin în imaginația liniștii.",
    "Persist în starea de armonie.",
    "Mă mențin în starea deja fiind echilibrat.",
    "Persist în imaginația păcii perfecte.",
    "Mă mențin în starea de liniște.",
    
    // Joe Dispenza - Consolidarea noii identități de liniște
    "Consolidez noua mea identitate calmă.",
    "Îmi întăresc identitatea de pace.",
    "Consolidez starea de liniște în creierul meu.",
    "Îmi întăresc identitatea de persoană calmă.",
    "Consolidez noua mea identitate de echilibru.",
    "Îmi întăresc identitatea de liniște.",
    "Consolidez starea de pace în mintea mea.",
    "Îmi întăresc identitatea de echilibru.",
    "Consolidez noua mea identitate de pace.",
    "Îmi întăresc identitatea de liniște.",
    
    // Louise Hay - Iubirea și acceptarea păcii
    "Îmi iubesc și accept liniștea din viața mea.",
    "Îmi iubesc relația mea cu pacea.",
    "Îmi accept toate formele de liniște.",
    "Îmi iubesc și accept toate aspectele echilibrului.",
    "Îmi accept pacea cu dragoste și gratitudine.",
    "Îmi iubesc și accept toate formele de armonie.",
    "Îmi accept liniștea cu bucurie.",
    "Îmi iubesc și accept toate momentele de calm.",
    "Îmi accept echilibrul cu recunoaștere.",
    "Îmi iubesc și accept toate aspectele păcii.",
    
    // Abraham Hicks - Vibrația constantă de liniște
    "Mențin vibrația liniștii în fiecare moment.",
    "Vibrația mea rămâne constantă în pace.",
    "Mențin energia liniștii în toate activitățile.",
    "Vibrația mea curge constant către liniște.",
    "Mențin rezonanța cu pacea.",
    "Vibrația mea rămâne aliniată cu liniștea.",
    "Mențin energia păcii în fiecare acțiune.",
    "Vibrația mea curge constant către echilibru.",
    "Mențin rezonanța cu liniștea infinită.",
    "Vibrația mea rămâne constantă în pace.",
    
    // Recunoaștere și oportunități - după-amiaza
    "Sunt recunoscător pentru toate momentele de liniște de azi.",
    "Mulțumesc pentru toate sursele de pace.",
    "Sunt recunoscător pentru toate aspectele echilibrului.",
    "Mulțumesc pentru toate oportunitățile de liniște.",
    "Sunt recunoscător pentru toate formele de pace.",
    "Mulțumesc pentru toate sursele de armonie.",
    "Sunt recunoscător pentru toate momentele de calm.",
    "Mulțumesc pentru liniștea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de pace.",
    "Mulțumesc pentru liniștea care curge prin mine.",
    
    // Oportunități și deschidere - după-amiaza
    "Sunt deschis la toate oportunitățile de liniște.",
    "Oportunitățile de pace vin către mine natural.",
    "Sunt deschis la toate formele de echilibru.",
    "Oportunitățile de liniște se deschid în fața mea.",
    "Sunt deschis la toate aspectele păcii.",
    "Oportunitățile de echilibru vin către mine ușor.",
    "Sunt deschis la toate formele de armonie.",
    "Oportunitățile de liniște se manifestă în viața mea.",
    "Sunt deschis la toate sursele de pace.",
    "Oportunitățile de echilibru curg prin mine.",
    
    // Dezvoltare și creștere - după-amiaza
    "Liniștea mea se dezvoltă și se îmbunătățește constant.",
    "Echilibrul meu se adâncesc în fiecare moment.",
    "Liniștea mea crește și se întărește natural.",
    "Echilibrul meu se dezvoltă și se îmbunătățesc.",
    "Liniștea mea se adâncesc și se întăresc.",
    "Echilibrul meu cresc și se dezvoltă.",
    "Liniștea mea se îmbunătățesc și se adâncesc.",
    "Echilibrul meu se întăresc și se dezvoltă.",
    "Liniștea mea se dezvoltă și se adâncesc.",
    "Echilibrul meu se îmbunătățesc și se întăresc.",
    
    // Meditație și conștiență - după-amiaza
    "Meditația mea este profundă și transformatoare.",
    "Sunt un magnet pentru momente de conștiență.",
    "Meditația mea se manifestă în toate aspectele vieții mele.",
    "Sunt un magnet pentru conștiență și pace.",
    "Meditația mea curge liber prin toate activitățile mele.",
    "Sunt un magnet pentru conștiență și liniște.",
    "Meditația mea se manifestă în toate formele de viață.",
    "Sunt un magnet pentru conștiență și echilibru.",
    "Meditația mea curge prin toate aspectele vieții mele.",
    "Sunt un magnet pentru conștiență și armonie.",
    
    // Respirație și relaxare - după-amiaza
    "Respirația mea este calmă și profundă.",
    "Sunt un magnet pentru momente de relaxare.",
    "Respirația mea se manifestă în toate aspectele vieții mele.",
    "Sunt un magnet pentru relaxare și pace.",
    "Respirația mea curge liber prin toate activitățile mele.",
    "Sunt un magnet pentru relaxare și liniște.",
    "Respirația mea se manifestă în toate formele de viață.",
    "Sunt un magnet pentru relaxare și echilibru.",
    "Respirația mea curge prin toate aspectele vieții mele.",
    "Sunt un magnet pentru relaxare și armonie.",
    
    // Mindfulness și prezență - după-amiaza
    "Sunt prezent în fiecare moment al vieții mele.",
    "Mindfulness-ul meu curge prin toate aspectele vieții mele.",
    "Sunt prezent în toate activitățile mele.",
    "Mindfulness-ul meu se manifestă în toate aspectele vieții mele.",
    "Sunt prezent în toate momentele de viață.",
    "Mindfulness-ul meu curge prin toate activitățile mele.",
    "Sunt prezent în toate aspectele vieții mele.",
    "Mindfulness-ul meu se manifestă în toate formele de viață.",
    "Sunt prezent în toate momentele de viață.",
    "Mindfulness-ul meu curge prin toate aspectele vieții mele.",
    
    // Succes și realizare - după-amiaza
    "Succesul în liniște este parte din identitatea mea.",
    "Sunt un magnet pentru realizări de pace.",
    "Succesul curge prin toate aspectele liniștii mele.",
    "Sunt un magnet pentru realizări de echilibru.",
    "Succesul se manifestă în toate formele de liniște.",
    "Sunt un magnet pentru realizări de pace.",
    "Succesul curge liber prin toate aspectele echilibrului meu.",
    "Sunt un magnet pentru realizări de liniște.",
    "Succesul se manifestă în toate formele de pace.",
    "Sunt un magnet pentru realizări de echilibru.",
    
    // Energia și vibrația - după-amiaza
    "Energia liniștii curge prin mine în fiecare moment.",
    "Vibrația mea atrage pace și echilibru.",
    "Energia păcii vibrează în fiecare celulă.",
    "Vibrația mea atrage liniște și armonie.",
    "Energia liniștii curge liber prin toate acțiunile mele.",
    "Vibrația mea atrage pace și liniște.",
    "Energia păcii vibrează în fiecare gând.",
    "Vibrația mea atrage echilibru și armonie.",
    "Energia liniștii curge prin toate aspectele vieții mele.",
    "Vibrația mea atrage pace și echilibru.",
    
    // Gratitudine și recunoaștere - după-amiaza
    "Sunt recunoscător pentru toate momentele de liniște din viața mea.",
    "Mulțumesc pentru toate sursele de pace.",
    "Sunt recunoscător pentru liniștea care curge prin mine.",
    "Mulțumesc pentru toate aspectele echilibrului din viața mea.",
    "Sunt recunoscător pentru pacea din viața mea.",
    "Mulțumesc pentru toate formele de liniște.",
    "Sunt recunoscător pentru toate momentele de calm.",
    "Mulțumesc pentru liniștea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de pace.",
    "Mulțumesc pentru liniștea care curge prin mine.",
    
    // Manifestare și creare - după-amiaza
    "Creez liniște perfectă prin acțiunile mele calme.",
    "Manifest pace prin alegerile mele înțelepte.",
    "Creez echilibru prin deschiderea mea la liniște.",
    "Manifest liniște prin afacerile mele de pace.",
    "Creez armonie prin perseverența mea în liniște.",
    "Manifest pace prin gratitudinea mea pentru liniște.",
    "Creez echilibru prin vibrația mea pozitivă constantă.",
    "Manifest liniște prin iubirea mea pentru pace.",
    "Creez armonie prin înțelepciunea mea în alegeri.",
    "Manifest liniște prin credința mea în pace infinită.",
    
    // Identitate și valoare - după-amiaza
    "Sunt o persoană calmă și echilibrată în toate aspectele.",
    "Identitatea mea reflectă liniștea și pacea constantă.",
    "Sunt demn de toate formele de liniște din Univers.",
    "Valoarea mea atrage pace natural și ușor.",
    "Sunt o persoană de succes în toate aspectele liniștii.",
    "Identitatea mea vibrează cu pacea infinită.",
    "Sunt demn de toate oportunitățile de liniște din lume.",
    "Valoarea mea se reflectă în liniștea din viața mea.",
    "Sunt o persoană care creează pace constantă.",
    "Identitatea mea este cea a unei persoane calme și fericite."
  ],
  
  // 🌙 SEARA - 100 afirmații (gratitudine și consolidare)
  evening: [
    // Neville Goddard - Gratitudinea pentru starea de liniște
    "Sunt recunoscător pentru starea de liniște perfectă.",
    "Mulțumesc pentru starea deja fiind calm.",
    "Sunt recunoscător pentru imaginația păcii.",
    "Mulțumesc pentru starea de echilibru complet.",
    "Sunt recunoscător pentru starea deja fiind în pace.",
    "Mulțumesc pentru imaginația liniștii.",
    "Sunt recunoscător pentru starea de armonie.",
    "Mulțumesc pentru starea deja fiind echilibrat.",
    "Sunt recunoscător pentru imaginația păcii perfecte.",
    "Mulțumesc pentru starea de liniște.",
    
    // Joe Dispenza - Integrarea noii identități de liniște
    "Integrez noua mea identitate calmă în fiecare seară.",
    "Îmi integrez identitatea de pace.",
    "Integrez starea de liniște în toate aspectele vieții mele.",
    "Îmi integrez identitatea de persoană calmă.",
    "Integrez noua mea identitate de echilibru în realitate.",
    "Îmi integrez identitatea de liniște.",
    "Integrez starea de pace în toate activitățile mele.",
    "Îmi integrez identitatea de echilibru.",
    "Integrez noua mea identitate de pace.",
    "Îmi integrez identitatea de liniște.",
    
    // Louise Hay - Iubirea și acceptarea completă
    "Îmi iubesc și accept complet liniștea din viața mea.",
    "Îmi iubesc relația mea cu pacea în toate formele.",
    "Îmi accept toate formele de liniște cu dragoste.",
    "Îmi iubesc și accept toate aspectele echilibrului.",
    "Îmi accept pacea cu dragoste, gratitudine și bucurie.",
    "Îmi iubesc și accept toate formele de armonie.",
    "Îmi accept liniștea cu bucurie și recunoaștere.",
    "Îmi iubesc și accept toate momentele de calm.",
    "Îmi accept echilibrul cu recunoaștere și gratitudine.",
    "Îmi iubesc și accept toate aspectele păcii.",
    
    // Abraham Hicks - Vibrația de gratitudine pentru liniște
    "Vibrația mea de gratitudine atrage liniște constantă.",
    "Vibrația mea de recunoaștere creează pace.",
    "Vibrația mea de gratitudine atrage echilibru.",
    "Vibrația mea de recunoaștere creează liniște.",
    "Vibrația mea de gratitudine atrage armonie.",
    "Vibrația mea de recunoaștere creează pace.",
    "Vibrația mea de gratitudine atrage liniște.",
    "Vibrația mea de recunoaștere creează echilibru.",
    "Vibrația mea de gratitudine atrage pace perfectă.",
    "Vibrația mea de recunoaștere creează liniște infinită.",
    
    // Gratitudine și recunoaștere - seara
    "Sunt recunoscător pentru toate momentele de liniște din viața mea.",
    "Mulțumesc pentru toate sursele de pace de azi.",
    "Sunt recunoscător pentru liniștea care curge prin mine.",
    "Mulțumesc pentru toate aspectele echilibrului din viața mea.",
    "Sunt recunoscător pentru pacea din viața mea.",
    "Mulțumesc pentru toate formele de liniște.",
    "Sunt recunoscător pentru toate momentele de calm.",
    "Mulțumesc pentru liniștea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de pace.",
    "Mulțumesc pentru liniștea care curge prin mine.",
    
    // Consolidare și integrare - seara
    "Consolidez liniștea în toate aspectele vieții mele.",
    "Integrez pacea în toate activitățile mele.",
    "Consolidez echilibrul în toate aspectele vieții mele.",
    "Integrez liniștea în toate formele de viață.",
    "Consolidez pacea în toate oportunitățile mele.",
    "Integrez echilibrul în toate aspectele vieții mele.",
    "Consolidez liniștea în toate sursele de pace.",
    "Integrez armonia în toate aspectele vieții mele.",
    "Consolidez pacea în toate formele de liniște.",
    "Integrez echilibrul în toate aspectele vieții mele.",
    
    // Reflectare și învățare - seara
    "Învăț din toate experiențele de liniște de azi.",
    "Reflectez asupra lecțiilor de pace din ziua de azi.",
    "Învăț din toate oportunitățile de liniște de azi.",
    "Reflectez asupra lecțiilor de echilibru din ziua de azi.",
    "Învăț din toate formele de pace de azi.",
    "Reflectez asupra lecțiilor de liniște din ziua de azi.",
    "Învăț din toate aspectele echilibrului de azi.",
    "Reflectez asupra lecțiilor de pace din ziua de azi.",
    "Învăț din toate oportunitățile de echilibru de azi.",
    "Reflectez asupra lecțiilor de liniște din ziua de azi.",
    
    // Pace și armonie - seara
    "Sunt în pace cu toate aspectele liniștii din viața mea.",
    "Armonia păcii curge prin toate aspectele vieții mele.",
    "Sunt în pace cu toate formele de echilibru.",
    "Armonia liniștii vibrează în fiecare moment.",
    "Sunt în pace cu toate aspectele păcii.",
    "Armonia echilibrului curge prin toate activitățile mele.",
    "Sunt în pace cu toate sursele de liniște.",
    "Armonia păcii vibrează în fiecare gând.",
    "Sunt în pace cu toate formele de armonie.",
    "Armonia liniștii curge prin toate aspectele vieții mele.",
    
    // Satisfacție și împlinire - seara
    "Sunt satisfăcut cu toate aspectele liniștii de azi.",
    "Împlinirea păcii curge prin toate aspectele vieții mele.",
    "Sunt satisfăcut cu toate formele de echilibru de azi.",
    "Împlinirea liniștii vibrează în fiecare moment.",
    "Sunt satisfăcut cu toate aspectele păcii de azi.",
    "Împlinirea echilibrului curge prin toate activitățile mele.",
    "Sunt satisfăcut cu toate sursele de liniște de azi.",
    "Împlinirea păcii vibrează în fiecare gând.",
    "Sunt satisfăcut cu toate formele de armonie de azi.",
    "Împlinirea liniștii curge prin toate aspectele vieții mele.",
    
    // Bucurie și fericire - seara
    "Sunt fericit cu toate aspectele liniștii din viața mea.",
    "Bucuria păcii curge prin toate aspectele vieții mele.",
    "Sunt fericit cu toate formele de echilibru.",
    "Bucuria liniștii vibrează în fiecare moment.",
    "Sunt fericit cu toate aspectele păcii din viața mea.",
    "Bucuria echilibrului curge prin toate activitățile mele.",
    "Sunt fericit cu toate sursele de liniște.",
    "Bucuria păcii vibrează în fiecare gând.",
    "Sunt fericit cu toate formele de armonie.",
    "Bucuria liniștii curge prin toate aspectele vieții mele.",
    
    // Manifestare și creare - seara
    "Creez liniște perfectă prin gratitudinea mea constantă.",
    "Manifest pace prin iubirea mea pentru liniște.",
    "Creez echilibru prin credința mea în pace.",
    "Manifest liniște prin perseverența mea în armonie.",
    "Creez pace prin înțelepciunea mea în alegeri.",
    "Manifest echilibru prin deschiderea mea la liniște.",
    "Creez armonie prin vibrația mea de gratitudine.",
    "Manifest liniște prin iubirea mea pentru pace.",
    "Creez pace prin credința mea în liniște infinită.",
    "Manifest echilibru prin gratitudinea mea pentru toate binecuvântările.",
    
    // Identitate și valoare - seara
    "Sunt o persoană calmă și echilibrată în toate aspectele vieții.",
    "Identitatea mea reflectă liniștea și pacea în toate formele.",
    "Sunt demn de toate formele de liniște din Univers.",
    "Valoarea mea atrage pace natural și ușor în toate aspectele.",
    "Sunt o persoană de succes în toate aspectele liniștii vieții.",
    "Identitatea mea vibrează cu pacea infinită și liniștea.",
    "Sunt demn de toate oportunitățile de liniște din lume.",
    "Valoarea mea se reflectă în liniștea din toate aspectele vieții mele.",
    "Sunt o persoană care creează pace constantă și liniște.",
    "Identitatea mea este cea a unei persoane calme, fericite și echilibrate."
  ]
};

