// ⚡ FOCUS ȘI PRODUCTIVITATE - 600 AFIRMAȚII
// Inspirat de Neville Goddard, Joe Dispenza, Louise Hay, Abraham Hicks

export const focus_600 = {
  // 🌅 DIMINEAȚA - 100 afirmații (energie și deschidere)
  morning: [
    // Neville Goddard - Imaginația și starea de focus
    "Sunt deja în starea de concentrare perfectă.",
    "Imaginația mea creează realitatea productivității.",
    "Sunt în starea deja fiind focalizat și productiv.",
    "Realitatea mea reflectă focusul din imaginația mea.",
    "Sunt deja în starea de eficiență completă.",
    "Imaginația mea este cheia concentrării mele.",
    "Sunt în starea deja fiind concentrat și eficient.",
    "Realitatea productivității se manifestă prin imaginația mea.",
    "Sunt deja în starea de focus perfect.",
    "Imaginația mea creează concentrarea în realitate.",
    
    // Joe Dispenza - Neuroplasticitate și focus
    "Îmi reprogramez creierul pentru concentrare perfectă.",
    "Noua mea identitate este cea a unei persoane productive.",
    "Îmi schimb starea interioară pentru focus.",
    "Creierul meu se reconectează pentru concentrare.",
    "Sunt în procesul de a deveni o persoană focalizată.",
    "Îmi creez o nouă identitate de productivitate.",
    "Starea mea interioară atrage concentrarea.",
    "Îmi reprogramez gândurile pentru focus.",
    "Sunt în transformare către productivitate completă.",
    "Noua mea identitate reflectă concentrarea perfectă.",
    
    // Louise Hay - Iubirea de sine și acceptarea productivității
    "Îmi iubesc și accept focusul în toate formele.",
    "Merit toate formele de concentrare și eficiență.",
    "Sunt demn de productivitate și focus.",
    "Îmi permit să fiu concentrat și productiv.",
    "Sunt în pace cu focusul și productivitatea mea.",
    "Îmi iubesc și accept toate aspectele concentrării.",
    "Sunt demn de toate oportunitățile de focus.",
    "Îmi accept concentrarea cu dragoste.",
    "Sunt în armonie cu toate formele de productivitate.",
    "Îmi iubesc și accept toate aspectele focusului.",
    
    // Abraham Hicks - Vibrația și atracția productivității
    "Vibrația mea atrage concentrarea natural.",
    "Sunt în aliniere cu energia productivității.",
    "Energia mea curge către focus.",
    "Sunt un magnet pentru concentrare și eficiență.",
    "Vibrația focusului curge prin mine.",
    "Sunt în rezonanță cu productivitatea.",
    "Energia mea atrage concentrare cu ușurință.",
    "Sunt în aliniere cu energia focusului perfect.",
    "Vibrația mea creează productivitate.",
    "Sunt un canal pentru energia concentrării.",
    
    // Afirmații combinate - dimineața
    "Sunt deja concentrat și productivitatea curge prin mine.",
    "Imaginația mea creează realitatea focusului perfect.",
    "Îmi reprogramez creierul pentru concentrare în fiecare dimineață.",
    "Îmi iubesc și accept toate formele de productivitate.",
    "Vibrația mea atrage focus și concentrare natural.",
    "Sunt în starea deja fiind focalizat și eficient.",
    "Noua mea identitate reflectă concentrarea perfectă.",
    "Îmi permit să fiu concentrat și productiv în toate aspectele.",
    "Energia focusului curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru concentrare și eficiență.",
    
    // Focus specific - dimineața
    "Concentrarea mea este puternică și neclintită.",
    "Sunt focalizat pe obiectivele mele cu claritate.",
    "Atenția mea este acută și precisă.",
    "Sunt în control asupra gândurilor mele.",
    "Concentrarea vine natural către mine.",
    "Sunt focalizat pe ceea ce este important.",
    "Atenția mea este stabilă și constantă.",
    "Sunt în control asupra atenției mele.",
    "Concentrarea mea se îmbunătățește în fiecare zi.",
    "Focusul este parte din identitatea mea.",
    
    // Productivitate și eficiență - dimineața
    "Productivitatea vine către mine natural și ușor.",
    "Sunt demn de toate oportunitățile de concentrare.",
    "Productivitatea este parte din identitatea mea.",
    "Sunt un magnet pentru momente de focus.",
    "Productivitatea curge prin toate aspectele vieții mele.",
    "Sunt recunoscător pentru toate oportunitățile de concentrare.",
    "Productivitatea este starea mea naturală.",
    "Sunt deschis la toate formele de focus.",
    "Eficiența vine către mine cu ușurință.",
    "Sunt un canal pentru energia productivității.",
    
    // Energie și deschidere - dimineața
    "Energia focusului curge prin mine în fiecare dimineață.",
    "Sunt deschis la toate oportunitățile de concentrare de azi.",
    "Energia productivității vine către mine din toate direcțiile.",
    "Sunt pregătit să primesc toate binecuvântările de focus.",
    "Energia concentrării vibrează în fiecare celulă a corpului meu.",
    "Sunt deschis la toate formele de productivitate.",
    "Energia focusului curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru oportunități de concentrare.",
    "Energia mea atrage focus și productivitate.",
    "Sunt deschis la toate sursele de concentrare infinită.",
    
    // Gratitudine și recunoaștere - dimineața
    "Sunt recunoscător pentru toate oportunitățile de focus din viața mea.",
    "Mulțumesc pentru toate sursele de productivitate.",
    "Sunt recunoscător pentru concentrarea care curge prin mine.",
    "Mulțumesc pentru toate aspectele eficienței din viața mea.",
    "Sunt recunoscător pentru productivitatea din viața mea.",
    "Mulțumesc pentru toate formele de concentrare.",
    "Sunt recunoscător pentru toate oportunitățile de focus.",
    "Mulțumesc pentru concentrarea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate aspectele productivității.",
    "Mulțumesc pentru focusul care curge prin mine.",
    
    // Manifestare și creare - dimineața
    "Creez focus perfect prin gândurile mele pozitive.",
    "Manifest productivitate în toate aspectele vieții mele.",
    "Creez concentrare prin intenția mea clară.",
    "Manifest focus prin credința mea în posibilități.",
    "Creez eficiență prin acțiunile mele înțelepte.",
    "Manifest productivitate prin gratitudinea mea pentru oportunități.",
    "Creez focus prin vibrația mea pozitivă.",
    "Manifest concentrare prin perseverența mea în productivitate.",
    "Creez oportunități prin deschiderea mea la focus.",
    "Manifest productivitate prin iubirea mea pentru viață.",
    
    // Identitate și valoare - dimineața
    "Sunt o persoană concentrată și productivă.",
    "Identitatea mea reflectă focusul și productivitatea.",
    "Sunt demn de toate oportunitățile de concentrare.",
    "Valoarea mea atrage focus natural.",
    "Sunt o persoană de productivitate în toate aspectele.",
    "Identitatea mea vibrează cu concentrarea.",
    "Sunt demn de toate formele de focus.",
    "Valoarea mea se reflectă în productivitatea din viața mea.",
    "Sunt o persoană care creează concentrare.",
    "Identitatea mea este cea a unei persoane focalizate.",
    
    // Acțiune și implementare - dimineața
    "Acționez cu înțelepciune pentru focus.",
    "Implementez strategii de productivitate.",
    "Acționez cu curaj pentru concentrare.",
    "Implementez planuri de focus.",
    "Acționez cu determinare pentru productivitate.",
    "Implementez strategii de concentrare.",
    "Acționez cu înțelepciune pentru eficiență.",
    "Implementez planuri de productivitate.",
    "Acționez cu curaj pentru focus.",
    "Implementez strategii de concentrare durabilă."
  ],
  
  // ☀️ DUPĂ-AMIAZA - 100 afirmații (recunoaștere și dezvoltare)
  afternoon: [
    // Neville Goddard - Persistența în starea de focus
    "Persist în starea de concentrare perfectă.",
    "Mă mențin în starea deja fiind focalizat.",
    "Persist în imaginația productivității.",
    "Mă mențin în starea de eficiență completă.",
    "Persist în starea deja fiind productiv.",
    "Mă mențin în imaginația focusului.",
    "Persist în starea de concentrare.",
    "Mă mențin în starea deja fiind eficient.",
    "Persist în imaginația productivității perfecte.",
    "Mă mențin în starea de focus.",
    
    // Joe Dispenza - Consolidarea noii identități de focus
    "Consolidez noua mea identitate focalizată.",
    "Îmi întăresc identitatea de productivitate.",
    "Consolidez starea de focus în creierul meu.",
    "Îmi întăresc identitatea de persoană productivă.",
    "Consolidez noua mea identitate de concentrare.",
    "Îmi întăresc identitatea de focus.",
    "Consolidez starea de productivitate în mintea mea.",
    "Îmi întăresc identitatea de concentrare.",
    "Consolidez noua mea identitate de productivitate.",
    "Îmi întăresc identitatea de focus.",
    
    // Louise Hay - Iubirea și acceptarea productivității
    "Îmi iubesc și accept focusul din viața mea.",
    "Îmi iubesc relația mea cu productivitatea.",
    "Îmi accept toate formele de concentrare.",
    "Îmi iubesc și accept toate aspectele focusului.",
    "Îmi accept productivitatea cu dragoste și gratitudine.",
    "Îmi iubesc și accept toate oportunitățile de focus.",
    "Îmi accept concentrarea cu bucurie.",
    "Îmi iubesc și accept toate formele de productivitate.",
    "Îmi accept focusul cu recunoaștere.",
    "Îmi iubesc și accept toate aspectele concentrării.",
    
    // Abraham Hicks - Vibrația constantă de focus
    "Mențin vibrația focusului în fiecare moment.",
    "Vibrația mea rămâne constantă în productivitate.",
    "Mențin energia concentrării în toate activitățile.",
    "Vibrația mea curge constant către focus.",
    "Mențin rezonanța cu productivitatea.",
    "Vibrația mea rămâne aliniată cu focusul.",
    "Mențin energia productivității în fiecare acțiune.",
    "Vibrația mea curge constant către concentrare.",
    "Mențin rezonanța cu focusul infinit.",
    "Vibrația mea rămâne constantă în productivitate.",
    
    // Recunoaștere și oportunități - după-amiaza
    "Sunt recunoscător pentru toate oportunitățile de focus de azi.",
    "Mulțumesc pentru toate sursele de productivitate.",
    "Sunt recunoscător pentru toate aspectele concentrării.",
    "Mulțumesc pentru toate oportunitățile de concentrare.",
    "Sunt recunoscător pentru toate formele de focus.",
    "Mulțumesc pentru toate sursele de eficiență.",
    "Sunt recunoscător pentru toate aspectele productivității.",
    "Mulțumesc pentru focusul care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de productivitate.",
    "Mulțumesc pentru concentrarea care curge prin mine.",
    
    // Oportunități și deschidere - după-amiaza
    "Sunt deschis la toate oportunitățile de focus.",
    "Oportunitățile de concentrare vin către mine natural.",
    "Sunt deschis la toate formele de productivitate.",
    "Oportunitățile de focus se deschid în fața mea.",
    "Sunt deschis la toate aspectele concentrării.",
    "Oportunitățile de productivitate vin către mine ușor.",
    "Sunt deschis la toate formele de eficiență.",
    "Oportunitățile de focus se manifestă în viața mea.",
    "Sunt deschis la toate sursele de concentrare.",
    "Oportunitățile de productivitate curg prin mine.",
    
    // Dezvoltare și creștere - după-amiaza
    "Focusul meu se dezvoltă și se îmbunătățește constant.",
    "Productivitatea mea se adâncesc în fiecare moment.",
    "Focusul meu crește și se întărește natural.",
    "Productivitatea mea se dezvoltă și se îmbunătățesc.",
    "Focusul meu se adâncesc și se întăresc.",
    "Productivitatea mea cresc și se dezvoltă.",
    "Focusul meu se îmbunătățesc și se adâncesc.",
    "Productivitatea mea se întăresc și se dezvoltă.",
    "Focusul meu se dezvoltă și se adâncesc.",
    "Productivitatea mea se îmbunătățesc și se întăresc.",
    
    // Concentrare și atenție - după-amiaza
    "Concentrarea mea este profundă și transformatoare.",
    "Sunt un magnet pentru momente de atenție.",
    "Concentrarea mea se manifestă în toate aspectele vieții mele.",
    "Sunt un magnet pentru atenție și focus.",
    "Concentrarea mea curge liber prin toate activitățile mele.",
    "Sunt un magnet pentru atenție și productivitate.",
    "Concentrarea mea se manifestă în toate formele de viață.",
    "Sunt un magnet pentru atenție și eficiență.",
    "Concentrarea mea curge prin toate aspectele vieții mele.",
    "Sunt un magnet pentru atenție și concentrare.",
    
    // Eficiență și organizare - după-amiaza
    "Eficiența mea este optimă și constantă.",
    "Sunt un magnet pentru momente de organizare.",
    "Eficiența mea se manifestă în toate aspectele vieții mele.",
    "Sunt un magnet pentru organizare și focus.",
    "Eficiența mea curge liber prin toate activitățile mele.",
    "Sunt un magnet pentru organizare și productivitate.",
    "Eficiența mea se manifestă în toate formele de viață.",
    "Sunt un magnet pentru organizare și concentrare.",
    "Eficiența mea curge prin toate aspectele vieții mele.",
    "Sunt un magnet pentru organizare și eficiență.",
    
    // Obiective și planificare - după-amiaza
    "Obiectivele mele sunt clare și realizabile.",
    "Sunt un magnet pentru planificare eficientă.",
    "Obiectivele mele se manifestă în toate aspectele vieții mele.",
    "Sunt un magnet pentru planificare și focus.",
    "Obiectivele mele curg liber prin toate activitățile mele.",
    "Sunt un magnet pentru planificare și productivitate.",
    "Obiectivele mele se manifestă în toate formele de viață.",
    "Sunt un magnet pentru planificare și concentrare.",
    "Obiectivele mele curg prin toate aspectele vieții mele.",
    "Sunt un magnet pentru planificare și eficiență.",
    
    // Succes și realizare - după-amiaza
    "Succesul în productivitate este parte din identitatea mea.",
    "Sunt un magnet pentru realizări de focus.",
    "Succesul curge prin toate aspectele concentrării mele.",
    "Sunt un magnet pentru realizări de productivitate.",
    "Succesul se manifestă în toate formele de focus.",
    "Sunt un magnet pentru realizări de concentrare.",
    "Succesul curge liber prin toate aspectele productivității mele.",
    "Sunt un magnet pentru realizări de focus.",
    "Succesul se manifestă în toate formele de concentrare.",
    "Sunt un magnet pentru realizări de productivitate.",
    
    // Energia și vibrația - după-amiaza
    "Energia focusului curge prin mine în fiecare moment.",
    "Vibrația mea atrage concentrare și productivitate.",
    "Energia concentrării vibrează în fiecare celulă.",
    "Vibrația mea atrage focus și eficiență.",
    "Energia focusului curge liber prin toate acțiunile mele.",
    "Vibrația mea atrage concentrare și productivitate.",
    "Energia concentrării vibrează în fiecare gând.",
    "Vibrația mea atrage focus și eficiență.",
    "Energia focusului curge prin toate aspectele vieții mele.",
    "Vibrația mea atrage concentrare și productivitate.",
    
    // Gratitudine și recunoaștere - după-amiaza
    "Sunt recunoscător pentru toate oportunitățile de focus din viața mea.",
    "Mulțumesc pentru toate sursele de productivitate.",
    "Sunt recunoscător pentru concentrarea care curge prin mine.",
    "Mulțumesc pentru toate aspectele eficienței din viața mea.",
    "Sunt recunoscător pentru productivitatea din viața mea.",
    "Mulțumesc pentru toate formele de concentrare.",
    "Sunt recunoscător pentru toate oportunitățile de focus.",
    "Mulțumesc pentru concentrarea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate aspectele productivității.",
    "Mulțumesc pentru focusul care curge prin mine.",
    
    // Manifestare și creare - după-amiaza
    "Creez focus perfect prin acțiunile mele înțelepte.",
    "Manifest productivitate prin alegerile mele corecte.",
    "Creez concentrare prin deschiderea mea la oportunități.",
    "Manifest focus prin afacerile mele de productivitate.",
    "Creez eficiență prin perseverența mea în concentrare.",
    "Manifest productivitate prin gratitudinea mea pentru oportunități.",
    "Creez focus prin vibrația mea pozitivă constantă.",
    "Manifest concentrare prin iubirea mea pentru productivitate.",
    "Creez eficiență prin înțelepciunea mea în planificare.",
    "Manifest focus prin credința mea în posibilități infinite.",
    
    // Identitate și valoare - după-amiaza
    "Sunt o persoană concentrată și productivă în toate aspectele.",
    "Identitatea mea reflectă focusul și productivitatea constantă.",
    "Sunt demn de toate oportunitățile de concentrare din Univers.",
    "Valoarea mea atrage focus natural și ușor.",
    "Sunt o persoană de succes în toate aspectele productivității.",
    "Identitatea mea vibrează cu concentrarea infinită.",
    "Sunt demn de toate formele de focus din lume.",
    "Valoarea mea se reflectă în productivitatea din viața mea.",
    "Sunt o persoană care creează concentrare constantă.",
    "Identitatea mea este cea a unei persoane focalizate și fericite."
  ],
  
  // 🌙 SEARA - 100 afirmații (gratitudine și consolidare)
  evening: [
    // Neville Goddard - Gratitudinea pentru starea de focus
    "Sunt recunoscător pentru starea de concentrare perfectă.",
    "Mulțumesc pentru starea deja fiind focalizat.",
    "Sunt recunoscător pentru imaginația productivității.",
    "Mulțumesc pentru starea de eficiență completă.",
    "Sunt recunoscător pentru starea deja fiind productiv.",
    "Mulțumesc pentru imaginația focusului.",
    "Sunt recunoscător pentru starea de concentrare.",
    "Mulțumesc pentru starea deja fiind eficient.",
    "Sunt recunoscător pentru imaginația productivității perfecte.",
    "Mulțumesc pentru starea de focus.",
    
    // Joe Dispenza - Integrarea noii identități de focus
    "Integrez noua mea identitate focalizată în fiecare seară.",
    "Îmi integrez identitatea de productivitate.",
    "Integrez starea de focus în toate aspectele vieții mele.",
    "Îmi integrez identitatea de persoană productivă.",
    "Integrez noua mea identitate de concentrare în realitate.",
    "Îmi integrez identitatea de focus.",
    "Integrez starea de productivitate în toate activitățile mele.",
    "Îmi integrez identitatea de concentrare.",
    "Integrez noua mea identitate de productivitate.",
    "Îmi integrez identitatea de focus.",
    
    // Louise Hay - Iubirea și acceptarea completă
    "Îmi iubesc și accept complet focusul din viața mea.",
    "Îmi iubesc relația mea cu productivitatea în toate formele.",
    "Îmi accept toate formele de concentrare cu dragoste.",
    "Îmi iubesc și accept toate aspectele focusului.",
    "Îmi accept productivitatea cu dragoste, gratitudine și bucurie.",
    "Îmi iubesc și accept toate oportunitățile de focus.",
    "Îmi accept concentrarea cu bucurie și recunoaștere.",
    "Îmi iubesc și accept toate formele de productivitate.",
    "Îmi accept focusul cu recunoaștere și gratitudine.",
    "Îmi iubesc și accept toate aspectele concentrării.",
    
    // Abraham Hicks - Vibrația de gratitudine pentru focus
    "Vibrația mea de gratitudine atrage focus constant.",
    "Vibrația mea de recunoaștere creează productivitate.",
    "Vibrația mea de gratitudine atrage oportunități de concentrare.",
    "Vibrația mea de recunoaștere creează focus.",
    "Vibrația mea de gratitudine atrage productivitate.",
    "Vibrația mea de recunoaștere creează concentrare.",
    "Vibrația mea de gratitudine atrage eficiență.",
    "Vibrația mea de recunoaștere creează productivitate.",
    "Vibrația mea de gratitudine atrage focus perfect.",
    "Vibrația mea de recunoaștere creează productivitate infinită.",
    
    // Gratitudine și recunoaștere - seara
    "Sunt recunoscător pentru toate oportunitățile de focus din viața mea.",
    "Mulțumesc pentru toate sursele de productivitate de azi.",
    "Sunt recunoscător pentru concentrarea care curge prin mine.",
    "Mulțumesc pentru toate aspectele eficienței din viața mea.",
    "Sunt recunoscător pentru productivitatea din viața mea.",
    "Mulțumesc pentru toate formele de concentrare.",
    "Sunt recunoscător pentru toate oportunitățile de focus.",
    "Mulțumesc pentru concentrarea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate aspectele productivității.",
    "Mulțumesc pentru focusul care curge prin mine.",
    
    // Consolidare și integrare - seara
    "Consolidez focusul în toate aspectele vieții mele.",
    "Integrez productivitatea în toate activitățile mele.",
    "Consolidez concentrarea în toate aspectele vieții mele.",
    "Integrez eficiența în toate formele de viață.",
    "Consolidez productivitatea în toate oportunitățile mele.",
    "Integrez focusul în toate aspectele vieții mele.",
    "Consolidez concentrarea în toate sursele de productivitate.",
    "Integrez eficiența în toate aspectele vieții mele.",
    "Consolidez productivitatea în toate formele de focus.",
    "Integrez concentrarea în toate aspectele vieții mele.",
    
    // Reflectare și învățare - seara
    "Învăț din toate experiențele de focus de azi.",
    "Reflectez asupra lecțiilor de productivitate din ziua de azi.",
    "Învăț din toate oportunitățile de concentrare de azi.",
    "Reflectez asupra lecțiilor de focus din ziua de azi.",
    "Învăț din toate formele de productivitate de azi.",
    "Reflectez asupra lecțiilor de concentrare din ziua de azi.",
    "Învăț din toate aspectele eficienței de azi.",
    "Reflectez asupra lecțiilor de focus din ziua de azi.",
    "Învăț din toate oportunitățile de productivitate de azi.",
    "Reflectez asupra lecțiilor de concentrare din ziua de azi.",
    
    // Pace și armonie - seara
    "Sunt în pace cu toate aspectele focusului din viața mea.",
    "Armonia productivității curge prin toate aspectele vieții mele.",
    "Sunt în pace cu toate formele de concentrare.",
    "Armonia focusului vibrează în fiecare moment.",
    "Sunt în pace cu toate aspectele productivității.",
    "Armonia concentrării curge prin toate activitățile mele.",
    "Sunt în pace cu toate sursele de focus.",
    "Armonia productivității vibrează în fiecare gând.",
    "Sunt în pace cu toate formele de eficiență.",
    "Armonia focusului curge prin toate aspectele vieții mele.",
    
    // Satisfacție și împlinire - seara
    "Sunt satisfăcut cu toate aspectele focusului de azi.",
    "Împlinirea productivității curge prin toate aspectele vieții mele.",
    "Sunt satisfăcut cu toate formele de concentrare de azi.",
    "Împlinirea focusului vibrează în fiecare moment.",
    "Sunt satisfăcut cu toate aspectele productivității de azi.",
    "Împlinirea concentrării curge prin toate activitățile mele.",
    "Sunt satisfăcut cu toate sursele de focus de azi.",
    "Împlinirea productivității vibrează în fiecare gând.",
    "Sunt satisfăcut cu toate formele de eficiență de azi.",
    "Împlinirea focusului curge prin toate aspectele vieții mele.",
    
    // Bucurie și fericire - seara
    "Sunt fericit cu toate aspectele focusului din viața mea.",
    "Bucuria productivității curge prin toate aspectele vieții mele.",
    "Sunt fericit cu toate formele de concentrare.",
    "Bucuria focusului vibrează în fiecare moment.",
    "Sunt fericit cu toate aspectele productivității din viața mea.",
    "Bucuria concentrării curge prin toate activitățile mele.",
    "Sunt fericit cu toate sursele de focus.",
    "Bucuria productivității vibrează în fiecare gând.",
    "Sunt fericit cu toate formele de eficiență.",
    "Bucuria focusului curge prin toate aspectele vieții mele.",
    
    // Manifestare și creare - seara
    "Creez focus perfect prin gratitudinea mea constantă.",
    "Manifest productivitate prin iubirea mea pentru concentrare.",
    "Creez concentrare prin credința mea în posibilități.",
    "Manifest focus prin perseverența mea în productivitate.",
    "Creez eficiență prin înțelepciunea mea în planificare.",
    "Manifest concentrare prin deschiderea mea la oportunități.",
    "Creez productivitate prin vibrația mea de gratitudine.",
    "Manifest focus prin iubirea mea pentru concentrare.",
    "Creez eficiență prin credința mea în productivitate infinită.",
    "Manifest concentrare prin gratitudinea mea pentru toate binecuvântările.",
    
    // Identitate și valoare - seara
    "Sunt o persoană concentrată și productivă în toate aspectele vieții.",
    "Identitatea mea reflectă focusul și productivitatea în toate formele.",
    "Sunt demn de toate oportunitățile de concentrare din Univers.",
    "Valoarea mea atrage focus natural și ușor în toate aspectele.",
    "Sunt o persoană de succes în toate aspectele productivității vieții.",
    "Identitatea mea vibrează cu concentrarea infinită și focusul.",
    "Sunt demn de toate formele de productivitate din lume.",
    "Valoarea mea se reflectă în focusul din toate aspectele vieții mele.",
    "Sunt o persoană care creează concentrare constantă și productivitate.",
    "Identitatea mea este cea a unei persoane focalizate, fericite și productive."
  ]
};



