// ❤️ IUBIRE ȘI RELAȚII - 600 AFIRMAȚII
// Inspirat de Neville Goddard, Joe Dispenza, Louise Hay, Abraham Hicks

export const iubire_600 = {
  // 🌅 DIMINEAȚA - 100 afirmații (deschidere și conexiune)
  morning: [
    // Neville Goddard - Imaginația și starea de iubire
    "Sunt deja în starea de iubire perfectă.",
    "Imaginația mea creează realitatea iubirii.",
    "Sunt în starea deja fiind iubit și iubind.",
    "Realitatea mea reflectă iubirea din imaginația mea.",
    "Sunt deja în starea de conexiune profundă.",
    "Imaginația mea este cheia iubirii mele.",
    "Sunt în starea deja fiind într-o relație perfectă.",
    "Realitatea iubirii se manifestă prin imaginația mea.",
    "Sunt deja în starea de iubire reciprocă.",
    "Imaginația mea creează iubirea în realitate.",
    
    // Joe Dispenza - Neuroplasticitate și iubirea
    "Îmi reprogramez creierul pentru iubire perfectă.",
    "Noua mea identitate este cea a unei persoane iubite.",
    "Îmi schimb starea interioară pentru conexiune profundă.",
    "Creierul meu se reconectează pentru iubire.",
    "Sunt în procesul de a deveni o persoană iubită.",
    "Îmi creez o nouă identitate de iubire.",
    "Starea mea interioară atrage iubirea.",
    "Îmi reprogramez gândurile pentru relații perfecte.",
    "Sunt în transformare către iubire completă.",
    "Noua mea identitate reflectă iubirea perfectă.",
    
    // Louise Hay - Iubirea de sine și acceptarea
    "Îmi iubesc și accept iubirea în toate formele.",
    "Merit toate formele de iubire și conexiune.",
    "Sunt demn de iubire și relații profunde.",
    "Îmi permit să primesc toate formele de iubire.",
    "Sunt în pace cu iubirea și relațiile mele.",
    "Îmi iubesc și accept toate aspectele iubirii.",
    "Sunt demn de toate conexiunile profunde.",
    "Îmi accept iubirea cu dragoste.",
    "Sunt în armonie cu toate formele de iubire.",
    "Îmi iubesc și accept toate aspectele conexiunii.",
    
    // Abraham Hicks - Vibrația și atracția iubirii
    "Vibrația mea atrage iubirea natural.",
    "Sunt în aliniere cu iubirea Universului.",
    "Energia mea curge către conexiuni profunde.",
    "Sunt un magnet pentru iubire și relații.",
    "Vibrația iubirii curge prin mine.",
    "Sunt în rezonanță cu conexiunile profunde.",
    "Energia mea atrage iubire cu ușurință.",
    "Sunt în aliniere cu iubirea infinită.",
    "Vibrația mea creează conexiuni perfecte.",
    "Sunt un canal pentru iubirea Universului.",
    
    // Afirmații combinate - dimineața
    "Sunt deja iubit și iubirea curge prin mine.",
    "Imaginația mea creează realitatea iubirii perfecte.",
    "Îmi reprogramez creierul pentru iubire în fiecare dimineață.",
    "Îmi iubesc și accept toate formele de conexiune.",
    "Vibrația mea atrage iubire și relații natural.",
    "Sunt în starea deja fiind într-o relație perfectă.",
    "Noua mea identitate reflectă iubirea infinită.",
    "Îmi permit să primesc toate formele de iubire.",
    "Energia iubirii curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru iubire și conexiuni profunde.",
    
    // Iubire specifică - dimineața
    "Iubirea vine către mine din toate direcțiile.",
    "Sunt deschis la toate oportunitățile de conexiune.",
    "Iubirea este starea mea naturală.",
    "Sunt un magnet pentru relații profunde.",
    "Conexiunile autentice mă găsesc ușor.",
    "Sunt recunoscător pentru toate formele de iubire.",
    "Iubirea circulă liber în viața mea.",
    "Sunt deschis la toate formele de conexiune.",
    "Relațiile profunde vin către mine natural.",
    "Sunt un magnet pentru iubire reciprocă.",
    
    // Conexiuni și relații - dimineața
    "Conexiunile profunde vin către mine natural și ușor.",
    "Sunt demn de toate formele de iubire.",
    "Conexiunea este parte din identitatea mea.",
    "Sunt un magnet pentru relații autentice.",
    "Conexiunile curg prin toate aspectele vieții mele.",
    "Sunt recunoscător pentru toate relațiile din viața mea.",
    "Conexiunea este starea mea naturală.",
    "Sunt deschis la toate formele de iubire.",
    "Relațiile profunde vin către mine cu ușurință.",
    "Sunt un canal pentru iubirea infinită.",
    
    // Energie și deschidere - dimineața
    "Energia iubirii curge prin mine în fiecare dimineață.",
    "Sunt deschis la toate oportunitățile de conexiune de azi.",
    "Energia conexiunii vine către mine din toate direcțiile.",
    "Sunt pregătit să primesc toate formele de iubire.",
    "Energia iubirii vibrează în fiecare celulă a corpului meu.",
    "Sunt deschis la toate formele de conexiune.",
    "Energia iubirii curge liber prin toate aspectele vieții mele.",
    "Sunt un magnet pentru oportunități de conexiune.",
    "Energia mea atrage iubire și relații profunde.",
    "Sunt deschis la toate sursele de iubire infinită.",
    
    // Gratitudine și recunoaștere - dimineața
    "Sunt recunoscător pentru toate formele de iubire din viața mea.",
    "Mulțumesc pentru toate conexiunile profunde.",
    "Sunt recunoscător pentru iubirea care curge prin mine.",
    "Mulțumesc pentru toate relațiile din viața mea.",
    "Sunt recunoscător pentru toate formele de conexiune.",
    "Mulțumesc pentru toate oportunitățile de iubire.",
    "Sunt recunoscător pentru toate relațiile autentice.",
    "Mulțumesc pentru iubirea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate conexiunile profunde.",
    "Mulțumesc pentru iubirea care curge prin mine.",
    
    // Manifestare și creare - dimineața
    "Creez iubire perfectă prin gândurile mele pozitive.",
    "Manifest conexiuni profunde în toate aspectele vieții mele.",
    "Creez relații autentice prin intenția mea clară.",
    "Manifest iubire prin credința mea în conexiune.",
    "Creez conexiuni prin acțiunile mele iubitoare.",
    "Manifest iubire prin gratitudinea mea pentru relații.",
    "Creez conexiuni prin vibrația mea pozitivă.",
    "Manifest iubire prin perseverența mea în conexiune.",
    "Creez relații prin deschiderea mea la iubire.",
    "Manifest conexiuni prin iubirea mea pentru viață.",
    
    // Identitate și valoare - dimineața
    "Sunt o persoană iubită și iubitoare.",
    "Identitatea mea reflectă iubirea și conexiunea.",
    "Sunt demn de toate formele de iubire.",
    "Valoarea mea atrage conexiuni naturale.",
    "Sunt o persoană de iubire în toate aspectele.",
    "Identitatea mea vibrează cu conexiunea.",
    "Sunt demn de toate oportunitățile de iubire.",
    "Valoarea mea se reflectă în iubirea din viața mea.",
    "Sunt o persoană care creează conexiuni.",
    "Identitatea mea este cea a unei persoane iubite.",
    
    // Acțiune și implementare - dimineața
    "Acționez cu înțelepciune pentru iubire.",
    "Implementez strategii de conexiune profundă.",
    "Acționez cu curaj pentru relații autentice.",
    "Implementez planuri de iubire.",
    "Acționez cu determinare pentru conexiuni.",
    "Implementez strategii de iubire.",
    "Acționez cu înțelepciune pentru relații.",
    "Implementez planuri de conexiune.",
    "Acționez cu curaj pentru iubire.",
    "Implementez strategii de conexiune durabilă."
  ],
  
  // ☀️ DUPĂ-AMIAZA - 100 afirmații (recunoaștere și dezvoltare)
  afternoon: [
    // Neville Goddard - Persistența în starea de iubire
    "Persist în starea de iubire perfectă.",
    "Mă mențin în starea deja fiind iubit.",
    "Persist în imaginația conexiunii profunde.",
    "Mă mențin în starea de relație perfectă.",
    "Persist în starea deja fiind într-o conexiune.",
    "Mă mențin în imaginația iubirii.",
    "Persist în starea de iubire reciprocă.",
    "Mă mențin în starea deja fiind conectat.",
    "Persist în imaginația relațiilor perfecte.",
    "Mă mențin în starea de iubire.",
    
    // Joe Dispenza - Consolidarea noii identități de iubire
    "Consolidez noua mea identitate de iubire.",
    "Îmi întăresc identitatea de conexiune profundă.",
    "Consolidez starea de iubire în creierul meu.",
    "Îmi întăresc identitatea de persoană iubită.",
    "Consolidez noua mea identitate de relație.",
    "Îmi întăresc identitatea de conexiune.",
    "Consolidez starea de iubire în mintea mea.",
    "Îmi întăresc identitatea de iubire.",
    "Consolidez noua mea identitate de conexiune.",
    "Îmi întăresc identitatea de relație.",
    
    // Louise Hay - Iubirea și acceptarea conexiunilor
    "Îmi iubesc și accept iubirea din viața mea.",
    "Îmi iubesc relația mea cu conexiunea.",
    "Îmi accept toate formele de iubire.",
    "Îmi iubesc și accept toate aspectele relațiilor.",
    "Îmi accept conexiunea cu dragoste și gratitudine.",
    "Îmi iubesc și accept toate formele de relații.",
    "Îmi accept iubirea cu bucurie.",
    "Îmi iubesc și accept toate conexiunile.",
    "Îmi accept relațiile cu recunoaștere.",
    "Îmi iubesc și accept toate aspectele iubirii.",
    
    // Abraham Hicks - Vibrația constantă de iubire
    "Mențin vibrația iubirii în fiecare moment.",
    "Vibrația mea rămâne constantă în conexiune.",
    "Mențin energia iubirii în toate activitățile.",
    "Vibrația mea curge constant către iubire.",
    "Mențin rezonanța cu conexiunile profunde.",
    "Vibrația mea rămâne aliniată cu iubirea.",
    "Mențin energia conexiunii în fiecare acțiune.",
    "Vibrația mea curge constant către relații.",
    "Mențin rezonanța cu iubirea infinită.",
    "Vibrația mea rămâne constantă în conexiune.",
    
    // Recunoaștere și oportunități - după-amiaza
    "Sunt recunoscător pentru toate formele de iubire de azi.",
    "Mulțumesc pentru toate conexiunile profunde.",
    "Sunt recunoscător pentru toate relațiile autentice.",
    "Mulțumesc pentru toate oportunitățile de conexiune.",
    "Sunt recunoscător pentru toate formele de relații.",
    "Mulțumesc pentru toate sursele de iubire.",
    "Sunt recunoscător pentru toate conexiunile.",
    "Mulțumesc pentru iubirea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate oportunitățile de iubire.",
    "Mulțumesc pentru conexiunea care curge prin mine.",
    
    // Oportunități și deschidere - după-amiaza
    "Sunt deschis la toate oportunitățile de iubire.",
    "Oportunitățile de conexiune vin către mine natural.",
    "Sunt deschis la toate formele de relații.",
    "Oportunitățile de iubire se deschid în fața mea.",
    "Sunt deschis la toate conexiunile profunde.",
    "Oportunitățile de relații vin către mine ușor.",
    "Sunt deschis la toate formele de iubire.",
    "Oportunitățile de conexiune se manifestă în viața mea.",
    "Sunt deschis la toate sursele de iubire.",
    "Oportunitățile de relații curg prin mine.",
    
    // Dezvoltare și creștere - după-amiaza
    "Relațiile mele se dezvoltă și se îmbunătățesc constant.",
    "Conexiunile mele se adâncesc în fiecare moment.",
    "Relațiile mele cresc și se întăresc natural.",
    "Conexiunile mele se dezvoltă și se îmbunătățesc.",
    "Relațiile mele se adâncesc și se întăresc.",
    "Conexiunile mele cresc și se dezvoltă.",
    "Relațiile mele se îmbunătățesc și se adâncesc.",
    "Conexiunile mele se întăresc și se dezvoltă.",
    "Relațiile mele se dezvoltă și se adâncesc.",
    "Conexiunile mele se îmbunătățesc și se întăresc.",
    
    // Autenticitate și sinceritate - după-amiaza
    "Toate relațiile mele sunt autentice și sincere.",
    "Sunt un magnet pentru conexiuni autentice.",
    "Toate relațiile mele sunt profunde și reale.",
    "Sunt un magnet pentru iubire autentică.",
    "Toate relațiile mele sunt sincere și adevărate.",
    "Sunt un magnet pentru conexiuni reale.",
    "Toate relațiile mele sunt autentice și profunde.",
    "Sunt un magnet pentru iubire sinceră.",
    "Toate relațiile mele sunt reale și autentice.",
    "Sunt un magnet pentru conexiuni sincere.",
    
    // Intimitate și apropiere - după-amiaza
    "Intimitatea curge prin toate aspectele relațiilor mele.",
    "Sunt un magnet pentru apropiere și intimitate.",
    "Intimitatea se manifestă în toate conexiunile mele.",
    "Sunt un magnet pentru apropiere profundă.",
    "Intimitatea curge liber prin toate relațiile mele.",
    "Sunt un magnet pentru intimitate și apropiere.",
    "Intimitatea se manifestă în toate aspectele conexiunilor mele.",
    "Sunt un magnet pentru apropiere și intimitate.",
    "Intimitatea curge prin toate formele de relații.",
    "Sunt un magnet pentru intimitate și apropiere.",
    
    // Comunicare și înțelegere - după-amiaza
    "Comunicarea curge liber în toate relațiile mele.",
    "Sunt un magnet pentru înțelegere și comunicare.",
    "Comunicarea se manifestă în toate conexiunile mele.",
    "Sunt un magnet pentru comunicare și înțelegere.",
    "Comunicarea curge liber prin toate aspectele relațiilor mele.",
    "Sunt un magnet pentru înțelegere și comunicare.",
    "Comunicarea se manifestă în toate formele de conexiuni.",
    "Sunt un magnet pentru comunicare și înțelegere.",
    "Comunicarea curge prin toate aspectele iubirii mele.",
    "Sunt un magnet pentru înțelegere și comunicare.",
    
    // Succes și realizare - după-amiaza
    "Succesul în relații este parte din identitatea mea.",
    "Sunt un magnet pentru realizări de iubire.",
    "Succesul curge prin toate aspectele conexiunilor mele.",
    "Sunt un magnet pentru realizări de relații.",
    "Succesul se manifestă în toate formele de iubire.",
    "Sunt un magnet pentru realizări de conexiune.",
    "Succesul curge liber prin toate aspectele relațiilor mele.",
    "Sunt un magnet pentru realizări de iubire.",
    "Succesul se manifestă în toate formele de conexiuni.",
    "Sunt un magnet pentru realizări de relații.",
    
    // Energia și vibrația - după-amiaza
    "Energia iubirii curge prin mine în fiecare moment.",
    "Vibrația mea atrage conexiuni profunde.",
    "Energia conexiunii vibrează în fiecare celulă.",
    "Vibrația mea atrage relații autentice.",
    "Energia iubirii curge liber prin toate acțiunile mele.",
    "Vibrația mea atrage conexiuni și iubire.",
    "Energia conexiunii vibrează în fiecare gând.",
    "Vibrația mea atrage relații și conexiuni.",
    "Energia iubirii curge prin toate aspectele vieții mele.",
    "Vibrația mea atrage iubire și conexiuni.",
    
    // Gratitudine și recunoaștere - după-amiaza
    "Sunt recunoscător pentru toate formele de iubire din viața mea.",
    "Mulțumesc pentru toate conexiunile profunde.",
    "Sunt recunoscător pentru iubirea care curge prin mine.",
    "Mulțumesc pentru toate relațiile din viața mea.",
    "Sunt recunoscător pentru toate formele de conexiune.",
    "Mulțumesc pentru toate oportunitățile de iubire.",
    "Sunt recunoscător pentru toate relațiile autentice.",
    "Mulțumesc pentru iubirea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate conexiunile profunde.",
    "Mulțumesc pentru iubirea care curge prin mine.",
    
    // Manifestare și creare - după-amiaza
    "Creez iubire perfectă prin acțiunile mele iubitoare.",
    "Manifest conexiuni profunde prin alegerile mele înțelepte.",
    "Creez relații autentice prin deschiderea mea la iubire.",
    "Manifest iubire prin afacerile mele de conexiune.",
    "Creez conexiuni prin perseverența mea în iubire.",
    "Manifest iubire prin gratitudinea mea pentru relații.",
    "Creez conexiuni prin vibrația mea pozitivă constantă.",
    "Manifest iubire prin iubirea mea pentru conexiuni.",
    "Creez relații prin înțelepciunea mea în comunicare.",
    "Manifest conexiuni prin credința mea în iubire infinită.",
    
    // Identitate și valoare - după-amiaza
    "Sunt o persoană iubită și iubitoare în toate aspectele.",
    "Identitatea mea reflectă iubirea și conexiunea constantă.",
    "Sunt demn de toate formele de iubire din Univers.",
    "Valoarea mea atrage conexiuni natural și ușor.",
    "Sunt o persoană de succes în toate aspectele iubirii.",
    "Identitatea mea vibrează cu conexiunea infinită.",
    "Sunt demn de toate oportunitățile de iubire din lume.",
    "Valoarea mea se reflectă în iubirea din viața mea.",
    "Sunt o persoană care creează conexiuni constantă.",
    "Identitatea mea este cea a unei persoane iubite și fericite."
  ],
  
  // 🌙 SEARA - 100 afirmații (gratitudine și consolidare)
  evening: [
    // Neville Goddard - Gratitudinea pentru starea de iubire
    "Sunt recunoscător pentru starea de iubire perfectă.",
    "Mulțumesc pentru starea deja fiind iubit.",
    "Sunt recunoscător pentru imaginația conexiunii profunde.",
    "Mulțumesc pentru starea de relație perfectă.",
    "Sunt recunoscător pentru starea deja fiind conectat.",
    "Mulțumesc pentru imaginația iubirii.",
    "Sunt recunoscător pentru starea de iubire reciprocă.",
    "Mulțumesc pentru starea deja fiind într-o conexiune.",
    "Sunt recunoscător pentru imaginația relațiilor perfecte.",
    "Mulțumesc pentru starea de iubire.",
    
    // Joe Dispenza - Integrarea noii identități de iubire
    "Integrez noua mea identitate de iubire în fiecare seară.",
    "Îmi integrez identitatea de conexiune profundă.",
    "Integrez starea de iubire în toate aspectele vieții mele.",
    "Îmi integrez identitatea de persoană iubită.",
    "Integrez noua mea identitate de relație în realitate.",
    "Îmi integrez identitatea de conexiune.",
    "Integrez starea de iubire în toate activitățile mele.",
    "Îmi integrez identitatea de iubire.",
    "Integrez noua mea identitate de conexiune.",
    "Îmi integrez identitatea de relație.",
    
    // Louise Hay - Iubirea și acceptarea completă
    "Îmi iubesc și accept complet iubirea din viața mea.",
    "Îmi iubesc relația mea cu conexiunea în toate formele.",
    "Îmi accept toate formele de iubire cu dragoste.",
    "Îmi iubesc și accept toate aspectele relațiilor.",
    "Îmi accept conexiunea cu dragoste, gratitudine și bucurie.",
    "Îmi iubesc și accept toate formele de relații.",
    "Îmi accept iubirea cu bucurie și recunoaștere.",
    "Îmi iubesc și accept toate conexiunile.",
    "Îmi accept relațiile cu recunoaștere și gratitudine.",
    "Îmi iubesc și accept toate aspectele iubirii.",
    
    // Abraham Hicks - Vibrația de gratitudine pentru iubire
    "Vibrația mea de gratitudine atrage iubire constantă.",
    "Vibrația mea de recunoaștere creează conexiuni profunde.",
    "Vibrația mea de gratitudine atrage relații autentice.",
    "Vibrația mea de recunoaștere creează iubire.",
    "Vibrația mea de gratitudine atrage conexiuni.",
    "Vibrația mea de recunoaștere creează relații.",
    "Vibrația mea de gratitudine atrage iubire.",
    "Vibrația mea de recunoaștere creează conexiuni.",
    "Vibrația mea de gratitudine atrage relații perfecte.",
    "Vibrația mea de recunoaștere creează iubire infinită.",
    
    // Gratitudine și recunoaștere - seara
    "Sunt recunoscător pentru toate formele de iubire din viața mea.",
    "Mulțumesc pentru toate conexiunile profunde de azi.",
    "Sunt recunoscător pentru iubirea care curge prin mine.",
    "Mulțumesc pentru toate relațiile din viața mea.",
    "Sunt recunoscător pentru toate formele de conexiune.",
    "Mulțumesc pentru toate oportunitățile de iubire.",
    "Sunt recunoscător pentru toate relațiile autentice.",
    "Mulțumesc pentru iubirea care se manifestă în viața mea.",
    "Sunt recunoscător pentru toate conexiunile profunde.",
    "Mulțumesc pentru iubirea care curge prin mine.",
    
    // Consolidare și integrare - seara
    "Consolidez iubirea în toate aspectele vieții mele.",
    "Integrez conexiunile profunde în toate activitățile mele.",
    "Consolidez relațiile în toate aspectele vieții mele.",
    "Integrez iubirea în toate formele de viață.",
    "Consolidez conexiunile în toate oportunitățile mele.",
    "Integrez iubirea în toate aspectele vieții mele.",
    "Consolidez relațiile în toate sursele de iubire.",
    "Integrez conexiunile în toate aspectele vieții mele.",
    "Consolidez iubirea în toate formele de conexiune.",
    "Integrez relațiile în toate aspectele vieții mele.",
    
    // Reflectare și învățare - seara
    "Învăț din toate experiențele de iubire de azi.",
    "Reflectez asupra lecțiilor de conexiune din ziua de azi.",
    "Învăț din toate oportunitățile de iubire de azi.",
    "Reflectez asupra lecțiilor de relații din ziua de azi.",
    "Învăț din toate formele de conexiune de azi.",
    "Reflectez asupra lecțiilor de iubire din ziua de azi.",
    "Învăț din toate aspectele relațiilor de azi.",
    "Reflectez asupra lecțiilor de conexiune din ziua de azi.",
    "Învăț din toate oportunitățile de relații de azi.",
    "Reflectez asupra lecțiilor de iubire din ziua de azi.",
    
    // Pace și armonie - seara
    "Sunt în pace cu toate aspectele iubirii din viața mea.",
    "Armonia conexiunilor curge prin toate aspectele vieții mele.",
    "Sunt în pace cu toate formele de relații.",
    "Armonia iubirii vibrează în fiecare moment.",
    "Sunt în pace cu toate aspectele conexiunilor.",
    "Armonia relațiilor curge prin toate activitățile mele.",
    "Sunt în pace cu toate sursele de iubire.",
    "Armonia conexiunilor vibrează în fiecare gând.",
    "Sunt în pace cu toate formele de iubire.",
    "Armonia relațiilor curge prin toate aspectele vieții mele.",
    
    // Satisfacție și împlinire - seara
    "Sunt satisfăcut cu toate aspectele iubirii de azi.",
    "Împlinirea conexiunilor curge prin toate aspectele vieții mele.",
    "Sunt satisfăcut cu toate formele de relații de azi.",
    "Împlinirea iubirii vibrează în fiecare moment.",
    "Sunt satisfăcut cu toate aspectele conexiunilor de azi.",
    "Împlinirea relațiilor curge prin toate activitățile mele.",
    "Sunt satisfăcut cu toate sursele de iubire de azi.",
    "Împlinirea conexiunilor vibrează în fiecare gând.",
    "Sunt satisfăcut cu toate formele de relații de azi.",
    "Împlinirea iubirii curge prin toate aspectele vieții mele.",
    
    // Bucurie și fericire - seara
    "Sunt fericit cu toate formele de iubire din viața mea.",
    "Bucuria conexiunilor curge prin toate aspectele vieții mele.",
    "Sunt fericit cu toate relațiile din viața mea.",
    "Bucuria iubirii vibrează în fiecare moment.",
    "Sunt fericit cu toate conexiunile din viața mea.",
    "Bucuria relațiilor curge prin toate activitățile mele.",
    "Sunt fericit cu toate aspectele iubirii din viața mea.",
    "Bucuria conexiunilor vibrează în fiecare gând.",
    "Sunt fericit cu toate formele de relații din viața mea.",
    "Bucuria iubirii curge prin toate aspectele vieții mele.",
    
    // Manifestare și creare - seara
    "Creez iubire perfectă prin gratitudinea mea constantă.",
    "Manifest conexiuni profunde prin iubirea mea pentru relații.",
    "Creez relații autentice prin credința mea în iubire.",
    "Manifest iubire prin perseverența mea în conexiune.",
    "Creez conexiuni prin înțelepciunea mea în relații.",
    "Manifest iubire prin deschiderea mea la conexiuni.",
    "Creez relații prin vibrația mea de gratitudine.",
    "Manifest conexiuni prin iubirea mea pentru iubire.",
    "Creez iubire prin credința mea în conexiuni infinite.",
    "Manifest relații prin gratitudinea mea pentru toate binecuvântările.",
    
    // Identitate și valoare - seara
    "Sunt o persoană iubită și iubitoare în toate aspectele vieții.",
    "Identitatea mea reflectă iubirea și conexiunea în toate formele.",
    "Sunt demn de toate formele de iubire din Univers.",
    "Valoarea mea atrage conexiuni natural și ușor în toate aspectele.",
    "Sunt o persoană de succes în toate aspectele iubirii vieții.",
    "Identitatea mea vibrează cu conexiunea infinită și iubirea.",
    "Sunt demn de toate oportunitățile de iubire din lume.",
    "Valoarea mea se reflectă în iubirea din toate aspectele vieții mele.",
    "Sunt o persoană care creează conexiuni constantă și iubire.",
    "Identitatea mea este cea a unei persoane iubite, fericite și conectate."
  ]
};


